service: lambda-nestjs-graphql-prisma

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 30 # attached to API Gateway so it's automatically limited to 30 seconds.
  profile: blinkers
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-offline

custom:
  webpack:
    includeModules:
      forceInclude:
        - prisma-nestjs-graphql # prisma ts type 파일 생성 라이브러리 (src/@generated)
      forceExclude:
        - aws-sdk
    packagerOptions:
      scripts:
        - prisma generate
        - npx rimraf "node_modules/@types"
        - npx rimraf "node_modules/aws-sdk"

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!.git/**"

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
